import React from "react";
import Navbar from "./navbar";
import styles from "./Layout.module.css";
import Head from "next/head";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/crud-app.png" />
      </Head>
      <Navbar />
      <main className={styles.container_main}>{children}</main>
    </>
  );
}

export default Layout;
